# Generated by Django 3.2.9 on 2021-12-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subnote',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
